apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-metrics
  labels:
    app: db-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-metrics
  template:
    metadata:
      labels:
        app: db-metrics
    spec:
      containers:
      - name: metrics
        image: guangbo/db-metrics:dev
        env:
        - name: INFLUXDB_SERVER
          value: "10.43.65.231"
        - name: INFLUXDB_PORT
          value: "8086"
        - name: MQTT_SERVER
          value: "10.43.111.82:1883"
        - name: MQTT_TOPIC
          value: "$cattle/device/#"
        - name: INFLUXDB_USERNAME
          value: "admin"
        - name: INFLUXDB_PASSWORD
          value: "dadmin"
